# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-09-11 20:08:46 +0200 by fabricehong:
gem "fastlane", "~> 2.104"
