# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-11-03 12:13:56 +0100 by fabricehong:
gem "cocoapods", "~> 1.5"
